CREATE DATABASE IF NOT EXISTS yeticave
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;
USE yeticave;

CREATE TABLE IF NOT EXISTS categories (
id INT AUTO_INCREMENT PRIMARY KEY,
cat_name VARCHAR(300)  NOT NULL  UNIQUE,
symb_code VARCHAR(150)  NOT NULL  UNIQUE
);

CREATE TABLE IF NOT EXISTS lots (
id INT AUTO_INCREMENT PRIMARY KEY,
user_create_id INT,
user_winner_id INT,
cat_id INT,
dt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
title VARCHAR(150),
img VARCHAR(255),
content TEXT,
start_price INT,
dt_end VARCHAR(255),
step_rate INT
);


CREATE TABLE IF NOT EXISTS rates  (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
lot_id INT,
dt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
rate_price INT
);

CREATE TABLE IF NOT EXISTS users  (
id INT AUTO_INCREMENT PRIMARY KEY,
lot_id INT,
rate_id INT,
dt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(300)  NOT NULL  UNIQUE,
login VARCHAR(300)  NOT NULL  UNIQUE,
pass VARCHAR(300)  NOT NULL  UNIQUE,
avatar VARCHAR(300),
contacts VARCHAR(300)
);
